### ISSUE TITLE
Insallation on yunohost fails

### ISSUE THREAD

**Issue by finster-** [matlink/torrelay_ynh#1]
## The installation of the tor relay fails:
- port=9091
- nickname=xxx_1
- contact=xxxt@xxx.xxx
- policy=No
- app=torrelay
- torconf=/etc/tor/torrc
- sudo yunohost app checkport 9091

Error: Port 9091 is not available
- [[ ! 22 -eq 0 ]]
- exit 1

---

**Comment by matlink** [comment]
What's running on your port 9091 ?

```
 netstat -plnt | grep 9091
```

and post results here,
thanks for report.

**Comment by finster-** [comment]
It looks like transmission is using the same port...

```
# netstat -plnt | grep 9091
tcp        0      0 127.0.0.1:9091          0.0.0.0:*               LISTEN      1942/transmission-d
```

**Comment by matlink** [comment]
Either change the Tor port at installation, or change the port used by transmission.

**Comment by finster-** [comment]
Changed port, up and running! Thanks a lot for that app!
